---
name: release
on:
  release:
    types: [published]
env:
  latest-python-version: 3.13
jobs:
  py-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: UV cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-${{ env.latest-python-version }}-uv-${{ hashFiles('pyproject.toml') }}
      - name: Install UV
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Python
        run: uv python install ${{ matrix.python-version }}
      - name: Build package
        run: uv build
      - name: Publish package
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish
